version: '3'
services:
  maplestory:
    build: .
    depends_on:
      - db
    ports:
      # Login server
      - "8484:8484"
      # Channels.
      # Format: WWCC, where WW is 75 plus the world number and CC is 75 plus the channel number (both zero indexed).
      # In this case, world 1 channels 1-3.
      - "7575-7577:7575-7577"
    expose:
      - 8484
      - 7575-7577
    volumes:
      # Config changes can be reloaded without rebuilding the image.
      # Still requires a redeployment as they're sourced on startup.
      - ./config.yaml:/opt/server/config.yaml
      - ./scripts:/opt/server/scripts
      - ./wz:/opt/server/wz
    environment:
      DB_HOST: "db"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: "nameless"
      #MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "123qwe"
      #MYSQL_PASSWORD: "123qwe"
    volumes:
      - ./database/docker-db-data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - 3306
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.05'
          memory: 512M
